### ISSUE TITLE
Code blocks start with `>` for weird edge case

### ISSUE THREAD

**Issue by killercup** [github/jekyll-commonmark-ghpages#1]
I'm currently trying to set up some nice doc rendering in <https://github.com/killercup/quicli/pull/24>. The challenge is this: I want to write guides in Markdown that Jekyll can render in a nice way, and that I can also convert to runnable/testable code with [waltz](https://github.com/killercup/waltz).

So far so commonly good markdown'd: waltz uses the pulldown-cmark crate, Jekyll has this plugin that uses cmark-gfm. So what formatting could possibly go wrong?

Well. Let me tell how about the way waltz decides which code blocks make up which files:

    ```rust,file=src/main.rs
    fn main() { println!("yolo"); }
    ```

See that weird rust-comma-file-equals stuff? Waltz parses that. It does, because it works for the code blocks Github renders (<https://github.com/killercup/waltz/issues/1>).

```rust,file=src/man.rs
fn main() { println!("yolo"); }
```

↑ Look at that perfect highlighting! In HTML, it becomes this:

```html
<div class="highlight highlight-source-rust">
  …
</div>
```

But who am I telling this. You probably know all of this already.

Now, my problem is this: When using `markdown: CommonMarkGhPages` in Jekyll, it renders the yolo-print block quoted above like this:

    <pre><code class="language-rust,file=src/main.rs">&gt;fn main() { println!("yolo"); }
    </code></pre>

Or, rendered:

<pre><code class="language-rust,file=src/main.rs">&gt;fn main() { println!("yolo"); }
</code></pre>

What is up with that `&gt;`? Where does it come from? (Nice that it's HTML-escaped at least!) Using the regular CommonMark plugin (`markdown: CommonMark`) prints the exact same HTML, except for that `>`.

I'd be super delighted if there was a way to get a `language-rust` without any `>`; but I can understand if you just want to fix the `>`, or if you close this issue linking me to the CommonMark spec section that says "DO NOT DO THIS, PASCAL."

**Comment by kivikakk** [comment]
What the. It works on github.com, so it should definitely work on Pages too. (At least, that's the ideal.) Technically the spec says you should use a space to separate additional information from the language (see [example 112 of the current version](http://spec.commonmark.org/0.28/#example-112)), but I'm still very curious why the behaviour differs between dotcom and Pages.

Looking into it!

**Comment by kivikakk** [comment]
Oh, of course; our syntax highlighting pass happens after Markdown to HTML conversion happens. It looks like this is "expected", for a certain value of expected.

`cmark` produces the weird HTML in whatever output mode we use for code blocks:

```console
$ cat input.md
```rust,file=a
hi
```
$ build/src/cmark-gfm input.md
<pre><code class="language-rust,file=a">hi
</code></pre>
$ build/src/cmark-gfm --github-pre-lang input.md
<pre lang="rust,file=a"><code>hi
</code></pre>
```

Our syntax highlighter searches for `rust,file=…` in the available highlighters and ends up matching `rust`, so this infelicity is never noticed.

`jekyll-commonmark-ghpages` currently [breaks on spaces to find the first word of the info block](https://github.com/github/jekyll-commonmark-ghpages/blob/c577bf2b0e45c976fb6cc2d1e363f95dc857568e/lib/jekyll-commonmark-ghpages.rb#L28-L30), so ideally that would be the syntax used by `waltz` instead. That said, I wouldn't be averse to breaking on `/[\s,]/`.

**Comment by killercup** [comment]
Thanks for looking into this! I hope this wasn't too disturbing of an issue to get on a Monday morning, @kivikakk :)

> Opening and closing spaces will be stripped, and the first word, prefixed with language-, is used as the value for the class attribute

Ah yes, the spec actually says what I should do. (No surprise there…)

I'm totally fine with switching the comma for a space! It honestly didn't occur to me to test this with more than two parsers, so this is totally my fault.

Do you want to add the comma splitting to jekyll-commonmark-ghpages so it conforms with what Github does? Otherwise feel free to close this issue :)

**Comment by killercup** [comment]
Toootally off topic question but also kinda related in my endeavor to deploy to Github Pages: Do you know of any way to have Pages builds triggered by bots or where to look? I'd really like to use [bors](https://bors.tech) and as the docs live in the same repo it should be able to trigger Pages builds. Sadly, I only get

![bildschirmfoto 2018-01-29 um 10 20 59](https://user-images.githubusercontent.com/20063/35503996-0c9cf84c-04e2-11e8-8e94-a2409f0bf25d.png)

(and surprisingly unhelpful search results).

**Comment by kivikakk** [comment]
> I hope this wasn't too disturbing of an issue to get on a Monday morning

Not at all, issues and questions are very welcome!

> Do you want to add the comma splitting to jekyll-commonmark-ghpages so it conforms with what Github does?

Good idea, I've done this now (d084e7b). It'll be a bit before it makes it into the Pages image, though.

> Do you know of any way to have Pages builds triggered by bots or where to look?

Super good question. I'll field this internally with the Pages people and see if we can get a resolution :+1:

**Comment by killercup** [comment]
Thanks so much! Feel free to cc me on anything related to this, I'd be happy to help/provide information/test stuff for you!

**Comment by kivikakk** [comment]
Just letting you know we're continuing to work through this; it's ended up being a mildly complicated infrastructure question, due to how Pages is put together.

**Comment by killercup** [comment]
Thanks for the update! <3 (I'm not blocked on this or anything.)

Ashe Connor <notifications@github.com> schrieb am Di. 30. Jan. 2018 um
02:07:

**Comment by kivikakk** [comment]
I'm gonna close this issue as the Pages trigger by an integration isn't strictly to do with this gem.

For an update on that issue, though: it ends up touching some core assumptions made by the system (namely, that an integration isn't allowed to get an OAuth token of its own, and Pages uses OAuth internally for authorisation). The appropriate teams are still looking into a solution, as it's a use-case we'd like to support, but I can't say when or if that'll land. 😞

**Comment by killercup** [comment]
Sure, the issue described here is resolved for me too.

Thanks for the update on the #borsrights initiative! I made enough typos to justify a lot of manual commits, so no need to hurry :)
