### ISSUE TITLE
Hyperlinks in markdown table are not links in GH pages rendering

### ISSUE THREAD

**Issue by wesinator** [github/jekyll-commonmark-ghpages#14]
https://github.com/wesinator/CTI-GroundTruths#binary-analysis-and-triage

https://wesinator.github.io/CTI-GroundTruths/#binary-analysis-and-triage

both empty theme and Cayman

**Comment by DirtyF** [comment]
Please read the installation documentation and add `autolink` extension.

https://dirtyf.github.io/CTI-GroundTruths/

**Comment by wesinator** [comment]
ok, thanks

links aren't rendered by default ?

**Comment by DirtyF** [comment]
Apparently, they're not, that's what the `autolink` option if for.

**Comment by wesinator** [comment]
> Apparently, they're not, that's what the `autolink` option if for.

yes, I meant why is this not the default for Github pages ? 
Shouldn't have to specify this in config IMO. Also , the default should be to open links in a new tab (target _blank).

Is there a yml config for opening links in new tab ?
I see hacky approach of adding target suffix in markdown, but then the markdown renders it as raw text (e.g. https://github.com/mind-maps/software/blob/master/index.md) 

Sorry if this is the wrong place to raise this, I'm not familiar with how Github pages is set up
