### ISSUE TITLE
Add "HARD_WRAP" option 

### ISSUE THREAD

**Issue by inwardmovement** [github/jekyll-commonmark-ghpages#2]
Is it possible to add an `HARD_WRAP` option like in kramdown, to parse markdown file's new lines into html line breaks?

**Comment by kivikakk** [comment]
You're in luck, it's already an option! If you specify this in `_config.yml`:

```yaml
commonmark:
  options: ["HARDBREAKS"]
```

you should get the desired result. :)

**Comment by inwardmovement** [comment]
Oh great! I didn't see it in the docs I searched in. When trying to install the gem (after switching back to kramdown) I have a message telling me to upgrade rubygems, and now I can't run "bundle exec" anymore, can't build Jekyll... so I have to fix this before trying the HARDBREAKS option. 

I must recognize I'm a bit sick of the ruby/gem ecosystem (there are often problems of this kind), I'll have to give Hugo a try haha.

**Comment by inwardmovement** [comment]
I've got a `CommonMark: HARDBREAKS is not a valid option` error

**Comment by inwardmovement** [comment]
I've got a `CommonMark: HARDBREAKS is not a valid option` error

**Comment by kivikakk** [comment]
Ah, this is a bug in https://github.com/jekyll/jekyll-commonmark which has been fixed … but there's not been a new version released since.

You should be able to pull the new release directly by adding the following to your `Gemfile`:

```ruby
gem "jekyll-commonmark", "1.1.0.1", :git => "https://github.com/jekyll/jekyll-commonmark.git"
```

Once done, update your bundle and this should work.

**Comment by inwardmovement** [comment]
So after reinstalling/updating all my gems I find myself with a new problem:
![image](https://user-images.githubusercontent.com/9438102/36087015-1d0947be-0fd0-11e8-9946-73bf415d481b.png)
This time a gem/bundler problem I think, aaarg... I could spend hours to try to fix this as usual, but I am moving my blog to Hugo, seems more maintainable/consistent with a simple binary, in the long term it would be more profitable. Anyways thanks for your help @kivikakk :)

**Comment by kivikakk** [comment]
No problems, I'm sorry the issues have been so many!

**Comment by inwardmovement** [comment]
I don't think I will use Jekyll, but I managed to fix my ruby/gem tools (I'm quite stubborn to fix something that doesn't work even if I switched to something else haha).  
Do you know why I have this error?

```
λ jekyll serve
Configuration file: C:/laragon/www/test/jekyll-test/_config.yml
            Source: C:/laragon/www/test/jekyll-test
       Destination: C:/laragon/www/test/jekyll-test/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
        CommonMark: HARDBREAKS is not a valid option
     Valid options: DEFAULT, VALIDATE_UTF8, SMART, LIBERAL_HTML_TAG, FOOTNOTES
                    done in 0.785 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'C:/laragon/www/test/jekyll-test'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```

with _congif.yml:

```
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "HARDBREAKS"]
  extensions: ["strikethrough", "autolink", "table"]
```

**Comment by kivikakk** [comment]
Have you tried making the `Gemfile` adjustment per above? Could you show me the contents of your `Gemfile.lock` file? This should only be the case with an older version of `jekyll-commonmark`.

**Comment by inwardmovement** [comment]
The Gemfile adjustment did it, thanks!
