### ISSUE TITLE
Future/status of this for GitHub Pages?

### ISSUE THREAD

**Issue by mb21** [github/jekyll-commonmark-ghpages#9]
What's the the plan for this for Github Pages?

I just set the markdown engine to [`CommonMarkGhPages`](https://github.com/github/jekyll-commonmark-ghpages) for a page, and got an email warning me to better change it to kramdown. The email linked to [Updating your Markdown processor to kramdown](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/). 

But as far as I know, kramdown is not commonmark-compliant, so is GitHub Pages just going to continue using a quite different flavour than the rest of github? Or was this email falsely triggered, assuming I was coming from redcarpet or something?

**Comment by kivikakk** [comment]
Your use here is correct -- that email is being sent in error. We actually internally call that renderer `gfm` and have been advising users to use that value, rather than `CommonMarkGhPages`, and weren't sending the email out in that case. I'll fix it so both values prevent the warning email.

**Comment by mb21** [comment]
Thanks, that's good to hear.

(I'm assuming `markdown: gfm` wouldn't work locally with this plugin..?)

**Comment by kivikakk** [comment]
> (I'm assuming `markdown: gfm` wouldn't work locally with this plugin..?)

That's correct -- we're doing it this way to hide the implementation detail of the exact name of the GFM renderer, and I didn't want to just call it `jekyll-gfm`. It's not clear to me that really got us anything, but oh well ¯\_(ツ)_/¯
